workflows:
  teka-teki-gambar-android:
    name: Teka-Teki Gambar - Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_ID: "com.game.tekatekigambar"
      node: 20
      java: 17
      android_signing:
        - Muhammad Fauzi
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*.*.*"
          include: true
      cancel_previous_builds: false

    scripts:
      - name: Install Cordova CLI
        script: |
          npm install -g cordova@13.0.0

      - name: Setup and Build Android App
        script: |
          set -e
          npm init -y
          cordova platform add android@13.0.0
          sdkmanager "build-tools;34.0.0"
          mkdir -p platforms/android/app/
          cp build-extras.gradle platforms/android/app/build-extras.gradle
          
          # Jalankan proses build aplikasi
          cordova build android --release -- --packageType=apk

    artifacts:
      - '**/build/outputs/apk/release/*.aab'
      - '**/build/outputs/apk/release/*.apk'

    publishing:
      email:
        recipients:
          - muhammadfauziarrasyid@gmail.com
        notify:
          success: true
          failure: true
          
